[project]
name = "installscripts"
version = "0.0.1b"
description = "install-scripts"
readme = "README.md"
requires-python = ">=3.13.13"
dependencies = [
    "bandit>=1.9.4",
    "pylint>=4.0.5",
    "pyrefly>=1.0.0",
    "pyright>=1.1.409",
    "ruff>=0.15.14",
]
license = "AGPL-3.0-only" 
license-files = ["LICENSE"]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
