[project]
name = "installscripts"
version = "0.0.1b"
description = "install-scripts"
readme = "README.md"
requires-python = ">=3.13.13"
dependencies = []
license = "MIT"
license-files = ["LICENSE"]

[dependency-groups]
dev = [
    "bandit>=1.9.4",
    "pre-commit>=4.6.0",
    "pylint>=4.0.5",
    "pyrefly>=1.0.0",
    "ruff>=0.15.14",
]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
