name: build deps
on: [push]

permissions:
  contents: write

jobs:
  format:
    name: go
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: './src/modules/gum/go.mod'
          cache: true
          cache-dependency-path: './src/modules/gum/go.sum'

      - name: Remove bin
        run: rm ./src/bin/* || echo "not built"

      - name: Build bin and copy LICENSE
        run: |
          cd ./src/modules/gum
          go build -o ../../bin/gum
          cp ./LICENSE ../../bin/LICENSE

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: Build bins
          branch: bins
          file_pattern: ./src/bin/*
          push_options: --force