name: build deps
on: [push]

permissions:
  contents: write

jobs:
  format:
    name: go
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: './src/modules/gum/go.mod'
          cache: true
          cache-dependency-path: './src/modules/gum/go.sum'

      - name: Remove bin
        run: rm ./src/bin/* || echo "not built"

      - name: Build bin and copy LICENSE
        run: |
          cd ./src/modules/gum
          go build -o ../../bin/gum
          cp ./LICENSE ../../bin/LICENSE

      - name: Commit changes to bins branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git checkout -B bins
          git add src/bin
          git commit -m "Build bins" || exit 0
          git push origin bins --force

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          base: master
          branch: bins
          title: "Add bins"
          body: "Auto-generated by GitHub Actions"